version: "3.9"

services:
  database:
    container_name: database
    image: postgres:15.2-alpine3.17

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.20
    ports:
      - 9090:80
