version: "3.9"

services:
  database:
    container_name: database
    image: postgres:15.2-alpine3.17
    environment:
      - POSTGRES_PASSWORD=words
      - POSTGRES_USER=words
    ports:
      - 9876:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.20
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - 9090:80
